---
  - hosts: webserver
    become: true
    tasks:
      - name: Install web-server
        yum: name={{item}} state=present update_cache=yes
        with_items:
          - httpd
          - python-pip
          - mod_wsgi

      - name: ensure web webserver started
        service: name=httpd state=started enabled=yes

      - name: ensure mod_wsgi started
        apache2_module: state=present name=wsgi
        notify: restart httpd

    handlers:
      - name: restart httpd
        service: name=httpd state=restarted
